version: '3.8'

services:
    frontend:
        image: react-documentflow
        build:
            context: .
            dockerfile: Dockerfile
        command: yarn start
        container_name: frontend
        ports:
            - 3001:3001
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true # to watch changes and refresh page if appears
